## Softmax

In [2]:
import numpy as np

In [55]:
vector = np.array([1203, 12312, 1133, 9999])

In [56]:
vector

array([ 1203, 12312,  1133,  9999])

In [57]:
def softmax(vec):
    exp = np.exp(vec)
    return exp / np.sum(exp)

In [58]:
softmax(vector)

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([nan, nan, nan, nan])

softmax 有一个问题，vector 过大，会导致小的值在 softmax 内概率为 null

In [8]:
def softmax_new(vec):
    vec -= np.max(vec)
    exp = np.exp(vec)
    return exp / np.sum(exp)

In [51]:
vector_1 = np.array([1000, 21341, 999, 13413])

In [52]:
vector_1

array([ 1000, 21341,   999, 13413])

In [53]:
softmax_new(vector_1)

array([0., 1., 0., 0.])

In [60]:
softmax_new(vector)

array([0., 1., 0., 0.])